spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aimory?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  issuer: aimory_server
  clientSecret: YWltb3J5IHNlY3JldCBjbGllbnQgdGVzdCBrZXk=
  expirySeconds: 3600

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com
    models:
      chat: gpt-3.5-turbo
      image: dall-e-3

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucketName: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
