spring:
    datasource:
        url: jdbc:mysql://localhost:3306/aimory?useSSL=false&serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
            format_sql: true
    profiles:
        active: private
openai:
    model: dall-e-3
    api:
        key: ${OPENAI_API_KEY}
        url: https://api.openai.com/v1/images/generations
