spring:
  datasource:
    url: jdbc:mysql://awseb-e-wmcbx2hvqk-stack-awsebrdsdatabase-c7gm27ehko98.ctyous2wke87.ap-northeast-2.rds.amazonaws.com/aimory?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

jwt:
  header: Authorization
  issuer: aimory_server
  clientSecret: ${JWT_CLIENT_SECRET}
  expirySeconds: 3600

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com
    models:
      chat: gpt-3.5-turbo
      image: dall-e-3

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucketName: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
